### ISSUE TITLE
Allow alternative blob seralizations

### ISSUE THREAD

**Issue by Gozala** [WebMemex/freeze-dry#42]
I would like to create service using freeze-dry that would essentially act as IPFS archiving proxy. I'm iterating on it here https://glitch.com/edit/#!/clone

Problem that I'm running into few issues:

1. Right now freez-dry attempts to create data URLs for everything, which is not what I would like to do, I want save data to the IPFS and use URL that would correspond to that. I did changes along those lines in the past https://github.com/Gozala/freeze-dry/commit/161c4fe8e108df5fd2bedb18ce4c5474404ef0dc would you be willing to accept pull that applies them on top of current master ?
2. Another issue I'm running into is that server often times-out before freeze-dry is finished. I'm starting to suspect that freezeDry fails silently (e.g. when loading https://clone.glitch.me/http://jeditoolkit.com/) I see all requests completing but promise never seems to resolve. Either way I would like to find a way for not having to fetch all resources before being able to serve response. Ideally API would allow me to update all referenced URLs and give me back updated markup without waiting to fetch them, allowing me to serve html and letting me to handle referenced resources on demand. Basic idea is that you don't necessarily need to finish creating a bundle. I'm not exactly sure yet how an API like that would look like but general idea would be something along these lines:

```js
const archive = freezeDry.archive(doc, {...})
// archive maintains map of resources that correspond to a document
// and .fetch returns either returns pending or fulfilled request corresponding to the
// resource URL. Or starts one if not initiated yet.
const page = await arhive.fetch(doc.URL)
// That way proxy server can serve requests from the archive as it's being
// build up.
const css = await archive.fetch(new URL('style.css', doc.URL))
// ....

// Completes whenever all of the resources are finished
const bundle = await archive.write({
  // 
  open: async (metadata) => new Bundler(),
  write: async (resource, bundler) => bundler.write(resource)
  close: async (bundler) => await bundler.writeToFile()
})
```

**Comment by Treora** [comment]
Sounds like a great tool, would love to have a http-to-ipfs converter like that.

Now that you make me think about the combination of these two issues you mention (which roughly correspond to #8 and #9), I realise my thinking about these issues was stuck because of a presumption of mine: I assumed one would always first need to have fetched a subresource before rewriting the link to it. When rewriting link targets to become data URLs this is obviously the case; but with a proxy you might rewrite the link target before (or simply without) fetching the content.

Though if the goal is to make IPFS URLs you would still need the content in order to calculate the hash, so in that case I don't see a way to start serving the HTML file before its full resource tree has been fetched.. so I suppose that is not the goal in your proxy. I guess you want to make an http proxy that delivers static html pages, and as a side-effect happens to store the page and each subresource on IPFS? I may be wrong here, but will assume this scenario for now to think about what changes freeze-dry would need to accomodate scenarios like this.

I could sketch this out as a **'proxy' recipe**:
1. Capture the DOM, find all its links to subresources.
2. Start crawling and storing subresources, but don't wait for this to finish.
3. 'Dry' the page (i.e. make links absolute, remove scripts, ...)
4. Rewrite the links to e.g. prefix them with the proxy URL, and possibly inline some resources if they are already available.
Then return/serve the DOM's HTML; which has some links to (proxied) subresources remaining (and of course the CSP should allow loading them).

The **current recipe** of freeze-dry is as follows: (see [`src/index.js`](https://github.com/WebMemex/freeze-dry/blob/master/src/index.js) or [`src/Readme.md`](https://github.com/WebMemex/freeze-dry/blob/master/src/Readme.md))
1. Capture the DOM, find all its links to subresources.
2. *Crawl all its subresources*
3. 'Dry' the page *and its subresources*
4. *Inline the subresources.*
Then it returns the DOM's HTML.

The main differences between the two recipes are indeed your two issues:
1. you should be able to customise how the new subresource URLs are created (i.e. a custom `blobToURL`, however it should also work if fetching the blob might not yet have completed!).
2. you should be able to control the crawling of the subresource tree.

I have a suspicion that there are too many ways people may want to perform their crawling, as well as their serialisation, to accomodate them all with API options. I am thinking that rather than creating a complex API where one can pass many callbacks, it may be easier to just expose the individual steps, so that you could write your own recipe (but perhaps you onto something similar, I don't think I fully understand the API you drafted). I wonder if for a scenario like this, you could solve your problems by replacing [`src/index.js`](https://github.com/WebMemex/freeze-dry/blob/master/src/index.js) with your own code, with hopefully only small changes to the other files (e.g. adding the `blobToURL` callback to `createSingleFile`). Perhaps some steps could be published as independent modules ([`src/extract-links`](https://github.com/WebMemex/freeze-dry/tree/master/src/extract-links) was already written with that in mind). I'd have to play with the code to find if it works, I should have some cycles to spare next week.

The `freezeDry()` function could then keep serving the simple use case that returns a self-contained string with data URLs, while more complex use cases will not call `freezeDry` itself, but rather invoke its steps. Does this direction sound reasonable or overcomplex/wrong-headed to you? Please let me know if you suspect I might be overlooking any issues.

**Comment by Gozala** [comment]
> Though if the goal is to make IPFS URLs you would still need the content in order to calculate the hash, so in that case I don't see a way to start serving the HTML file before its full resource tree has been fetched.. so I suppose that is not the goal in your proxy. I guess you want to make an http proxy that delivers static html pages, and as a side-effect happens to store the page and each subresource on IPFS? I may be wrong here, but will assume this scenario for now to think about what changes freeze-dry would need to accomodate scenarios like this.

Idea is that https://clone.glitch.me/http://jeditoolkit.com/ will start serving a page with all resources rewritten as relative URLs which would also hit the proxy and be served through `archive.fetch`. as things are fetched they also get bundled (through that write API sketched) and when whole thing is complete page will communicate new address with a visitor. How to do the last part is not fully clear in my mind yet, in worst case connection to first request will remain open and some script will be added at the end to do `location.pushState` or something along those lines

**Comment by Gozala** [comment]
I think what you want to change about API is

1. Introduce `resolveResource` that returns promise which resolves to whatever consumer wants let’s call it "request” that needs to have `url` property which will be used for resource rewrite. Then `fetchResource(request)` is used that must return `Response` promise (archive will maintain url to “response” promise map to use in `archive.fetch`), succeeded response + url is then passed into `writeResource(bundle, {url, response})` that will do archiving (to IPFS or whatever) once all resources are archived bundle will have completed doing it’s job and can have overall hash or a single file with everything inlined

**Comment by Gozala** [comment]
@Treora I've started drafting a version that could accomplish both full inlining & lazy streaming bundler. I'm afraid it's not going to be trivial set of changes because there are few very contradicting constraints based on use cases:

- When you want to generate a single data URL, you pre-fetch everything so you can start inlining from the leaf resources.
- When you want to start streaming as soon as possible you do want to go other way round from top resource to down the tree. And you want to avoid fetching resources whenever it's possible to just update URL, deferring fetching. Which in turns implies that you need to continue crawling on demand.

This led me to design where resources are represented in a lazy glorified pair of `(io, link)` where former is set of functions that can fetch **resource** and resolve **resource** URL. And since **resource**. It also has continence methods to serialize a resource. That last bit is where things start to get interesting. When serialization is initiated it will fetch corresponding data, do a shallow crawl to yield sub-resources & resolve their URLs via (io). Resolution is customizable, meaning `resolveURL(resource):Promise<URL>` which provides io provider a choice:

- serialize the sub-resource first to generate data url, meaning it will recurse the process and end up doing depth first. 
- return whatever URL (e.g relative) one without fetching any data or crawling resource. This would enable proxy use case as resource links will just get swapped and things move forward. Other resources will be serialized / crawled on demand.
- some hybrid of above two, where you can do partial work (or schedule some work) but avoid waiting e.g. relative resources could be proxied and extrenal resources inlined.

I published current draft (which I have never run, so probably it's not working) but I thought I'd share it anyhow:

https://github.com/Gozala/freeze-dry/blob/91d7926a5e8e2a2b8a3fc3e40c27814e2fa4979d/src/archiver.js#L1-L438
